baseURL = "https://www.yunxi.abrdns.com/"  # 改成你的 Cloudflare Pages 自定义域名
languageCode = "zh-cn"
title = "明心的博客"
theme = "PaperMod"

# URL 配置，保证文章和页面能正确访问
uglyURLs = false       # 使用 /posts/first-article/ 形式，而不是 .html
relativeURLs = true    # 生成相对路径，适合静态部署
canonifyURLs = true    # 自动规范 URL

[params]
defaultTheme = "auto"

[params.homeInfoParams]
Title = "你好，我是明心"
Content = "欢迎来到我的博客主页：个人 / 博客 / 教程"

[[menu.main]]
name = "个人"
url = "/posts"
weight = 1

[[menu.main]]
name = "教程"
url = "/docs"
weight = 2

[[menu.main]]
name = "学习"
url = "/study"
weight = 3
